const fruitsInfo = [
  {
    fruitName: "apple",
    Binomial_Name: "Malus domestica",
    genus: "Malus",
    family: "Rosaceae",
    origin: "Central Asia",
    fruitType: "Pome",
    description:
      "A round, red or green fruit with a crisp flesh and a sweet or tart flavor. Apples are a good source of fiber and vitamin C.",
    nutritional_information: {
      Calories: 95,
      Fat: "0.3 g",
      Carbohydrates: "25 g",
      Fiber: "4.5 g",
      Sugar: "19 g",
      Protein: "1 g",
      "Vitamin C": "14 mg",
      Potassium: "147 mg",
      Calcium: "10 mg",
      Magnesium: "11 mg",
      Iron: "1 mg",
      Phosphorus: "24 mg",
      Zinc: "0.5 mg",
    },
    health_benefits: [
      "May help reduce the risk of heart disease",
      "May help reduce the risk of stroke",
      "May help protect against some types of cancer",
      "May help improve digestion",
      "May help improve cognitive function",
      "May help boost the immune system",
      "May help improve skin health",
    ],
    seasonality: "Fall and Winter",
    allergenicity: "No",
    price: "$1.00 - $2.00 per pound",
  },

  {
    fruitName: "banana",
    Binomial_Name: "Musa acuminata",
    genus: "Musa",
    family: "Musaceae",
    origin: "Southeast Asia",
    fruitType: "Berry",
    description:
      "A long, yellow fruit with a soft flesh and a sweet flavor. Bananas are a good source of potassium and vitamin B6.",
    nutritional_information: {
      Calories: 105,
      Fat: "0.3 g",
      Carbohydrates: "27 g",
      Fiber: "3.1 g",
      Sugar: "22 g",
      Protein: "1 g",
      "Vitamin C": "10 mg",
      Potassium: "422 mg",
      Calcium: "10 mg",
      Magnesium: "32 mg",
      Iron: "1 mg",
      Phosphorus: "31 mg",
      Zinc: "0.5 mg",
    },
    health_benefits: [
      "May help improve digestion",
      "May help reduce the risk of stroke",
      "May help improve heart health",
      "May help boost the immune system",
      "May help improve muscle strength",
      "May help improve cognitive function",
      "May help prevent kidney stones",
    ],
    seasonality: "Year-round",
    allergenicity: "No",
    price: "$0.50 - $1.00 per pound",
  },
  {
    fruitName: "beetroot",
    Binomial_Name: "Beta vulgaris",
    genus: "Beta",
    family: "Chenopodiaceae",
    origin: "Mediterranean region",
    fruitType: "Root vegetable",
    description:
      "A round, red root vegetable with a earthy flavor. Beetroot is a good source of fiber, folate, and vitamin C.",
    nutritional_information: {
      Calories: 43,
      Fat: "0.1 g",
      Carbohydrates: "10 g",
      Fiber: "2.8 g",
      Sugar: "4.7 g",
      Protein: "1.8 g",
      "Vitamin C": "16 mg",
      Folate: "134 mcg",
      Potassium: "216 mg",
      Calcium: "14 mg",
      Magnesium: "22 mg",
      Iron: "1 mg",
      Phosphorus: "36 mg",
    },
    health_benefits: [
      "May help improve blood flow",
      "May help lower blood pressure",
      "May help improve athletic performance",
      "May help protect against cancer",
      "May help improve gut health",
      "May help boost the immune system",
      "May help improve skin health",
    ],
    seasonality: "Summer and Fall",
    allergenicity: "No",
    price: "$1.00 - $2.00 per pound",
  },
  {
    fruitName: "chilli pepper",
    Binomial_Name: "Capsicum annuum",
    genus: "Capsicum",
    family: "Solanaceae",
    origin: "Mexico",
    fruitType: "Capsicum",
    description:
      "A small, hot or mild fruit with a spicy flavor. Chilli peppers are a good source of vitamin C and capsaicin.",
    nutritional_information: {
      Calories: "40",
      Fat: "0.1 g",
      Carbohydrates: "9 g",
      Fiber: "2.5 g",
      Sugar: "4.8 g",
      Protein: "1.1 g",
      "Vitamin C": "152 mg",
      Capsaicin: "0.3 - 0.5 mg",
      Potassium: "245 mg",
      Calcium: "14 mg",
      Magnesium: "22 mg",
      Iron: "0.5 mg",
      Phosphorus: "36 mg",
    },
    health_benefits: [
      "May help improve vision",
      "May help protect against cancer",
      "May help boost the immune system",
      "May help improve heart health",
      "May help improve skin health",
      "May help improve digestion",
      "May help reduce inflammation",
    ],
    seasonality: "Summer and Fall",
    allergenicity: "No",
    price: "20 - 40 INR per kilogram",
  },
  {
    fruitName: "corn",
    Binomial_Name: "Zea mays",
    genus: "Zea",
    family: "Poaceae",
    origin: "Mexico",
    fruitType: "Grain",
    description:
      "A large, yellow or white grain with a sweet or savory flavor. Corn is a good source of carbohydrates, fiber, and vitamin C.",
    nutritional_information: {
      Calories: "150",
      Fat: "1 g",
      Carbohydrates: "30 g",
      Fiber: "3 g",
      Sugar: "18 g",
      Protein: "4 g",
      "Vitamin C": "12 mg",
      Potassium: "276 mg",
      Calcium: "10 mg",
      Magnesium: "32 mg",
      Iron: "1 mg",
      Phosphorus: "36 mg",
    },
    health_benefits: [
      "May help improve heart health",
      "May help protect against cancer",
      "May help boost the immune system",
      "May help improve vision",
      "May help improve skin health",
      "May help improve digestion",
      "May help reduce inflammation",
    ],
    seasonality: "Summer",
    allergenicity: "No",
    price: "30 - 50 INR per kilogram",
  },
  {
    fruitName: "garlic",
    Binomial_Name: "Allium sativum",
    genus: "Allium",
    family: "Amaryllidaceae",
    origin: "Central Asia",
    fruitType: "Bulb",
    description:
      "A pungent bulb composed of several cloves, commonly used as a seasoning and flavoring ingredient in various cuisines.",
    nutritional_information: {
      Calories: "149",
      Fat: "0.5 g",
      Carbohydrates: "33 g",
      Fiber: "2.1 g",
      Sugar: "1 g",
      Protein: "6 g",
      "Vitamin C": "31.2 mg",
      Potassium: "401 mg",
      Calcium: "18 mg",
      Magnesium: "25 mg",
      Iron: "1.7 mg",
      Phosphorus: "153 mg",
      Zinc: "1.2 mg",
    },
    health_benefits: [
      "May help boost the immune system",
      "May help reduce blood pressure",
      "May help improve heart health",
      "May have anticancer properties",
      "May help improve cholesterol levels",
      "May have antibacterial and antifungal properties",
    ],
    seasonality: "Year-round",
    allergenicity: "No",
    price: "₹120 - ₹150 per kilogram",
  },
  {
    fruitName: "ginger",
    Binomial_Name: "Zingiber officinale",
    genus: "Zingiber",
    family: "Zingiberaceae",
    origin: "Southeast Asia",
    fruitType: "Rhizome",
    description:
      "A knobby, aromatic rhizome used as a spice and traditional medicine in many cultures. It has a spicy and pungent flavor.",
    nutritional_information: {
      Calories: "80",
      Fat: "0.8 g",
      Carbohydrates: "18 g",
      Fiber: "2 g",
      Sugar: "1.7 g",
      Protein: "1.8 g",
      "Vitamin C": "5 mg",
      Potassium: "415 mg",
      Calcium: "16 mg",
      Magnesium: "43 mg",
      Iron: "0.6 mg",
      Phosphorus: "34 mg",
      Zinc: "0.3 mg",
    },
    health_benefits: [
      "May help reduce nausea and vomiting",
      "May help reduce muscle pain and soreness",
      "May help lower blood sugar levels",
      "May help reduce menstrual pain",
      "May have anti-inflammatory effects",
      "May help improve brain function",
    ],
    seasonality: "Year-round",
    allergenicity: "No",
    price: "₹70 - ₹90 per kilogram",
  },
  {
    fruitName: "grapes",
    Binomial_Name: "Vitis vinifera",
    genus: "Vitis",
    family: "Vitaceae",
    origin: "Western Asia",
    fruitType: "Berry",
    description:
      "Small, sweet or sour berries that grow in clusters on vines. Grapes are often used for making wine and can be eaten fresh or dried as raisins.",
    nutritional_information: {
      Calories: "69",
      Fat: "0.2 g",
      Carbohydrates: "18 g",
      Fiber: "0.9 g",
      Sugar: "16 g",
      Protein: "0.7 g",
      "Vitamin C": "3.2 mg",
      Potassium: "191 mg",
      Calcium: "10 mg",
      Magnesium: "7 mg",
      Iron: "0.4 mg",
      Phosphorus: "20 mg",
      Zinc: "0.1 mg",
    },
    health_benefits: [
      "May help protect against heart disease",
      "May help improve brain function",
      "May have anticancer properties",
      "May help maintain healthy blood pressure",
      "May aid digestion",
      "May support eye health",
    ],
    seasonality: "Summer and Fall",
    allergenicity: "No",
    price: "₹80 - ₹120 per kilogram",
  },
  {
    fruitName: "jalepeno",
    Binomial_Name: "Capsicum annuum",
    genus: "Capsicum",
    family: "Solanaceae",
    origin: "Mexico",
    fruitType: "Pepper",
    description:
      "A medium-sized chili pepper with a mild to moderate heat level. Jalapenos are commonly used in Mexican cuisine and can be eaten fresh or pickled.",
    nutritional_information: {
      Calories: "26",
      Fat: "0.6 g",
      Carbohydrates: "4.8 g",
      Fiber: "1.7 g",
      Sugar: "1.4 g",
      Protein: "0.9 g",
      "Vitamin C": "66 mg",
      Potassium: "252 mg",
      Calcium: "7 mg",
      Magnesium: "10 mg",
      Iron: "0.4 mg",
      Phosphorus: "19 mg",
      Zinc: "0.2 mg",
    },
    health_benefits: [
      "May aid digestion",
      "May help boost metabolism",
      "May have antibacterial properties",
      "May help reduce inflammation",
      "May promote weight loss",
      "May support cardiovascular health",
    ],
    seasonality: "Year-round",
    allergenicity: "No",
    price: "₹100 - ₹150 per kilogram",
  },
  {
    fruitName: "kiwi",
    Binomial_Name: "Actinidia deliciosa",
    genus: "Actinidia",
    family: "Actinidiaceae",
    origin: "China",
    fruitType: "Berry",
    description:
      "A small, oval fruit with fuzzy brownish-green skin and bright green flesh. Kiwi has a sweet and tangy flavor with a hint of tartness.",
    nutritional_information: {
      Calories: "61",
      Fat: "0.5 g",
      Carbohydrates: "15 g",
      Fiber: "3 g",
      Sugar: "9 g",
      Protein: "1.1 g",
      "Vitamin C": "64 mg",
      Potassium: "312 mg",
      Calcium: "34 mg",
      Magnesium: "17 mg",
      Iron: "0.3 mg",
      Phosphorus: "34 mg",
      Zinc: "0.1 mg",
    },
    health_benefits: [
      "May boost immune system",
      "May support digestive health",
      "May aid in managing blood pressure",
      "May improve skin health",
      "May have anticancer properties",
      "May promote healthy vision",
    ],
    seasonality: "Winter and Spring",
    allergenicity: "No",
    price: "₹120 - ₹180 per kilogram",
  },
  {
    fruitName: "lemon",
    Binomial_Name: "Citrus limon",
    genus: "Citrus",
    family: "Rutaceae",
    origin: "Asia",
    fruitType: "Citrus",
    description:
      "A small, yellow citrus fruit known for its acidic juice and refreshing flavor. Lemons are used in cooking, baking, and as a garnish.",
    nutritional_information: {
      Calories: "29",
      Fat: "0.3 g",
      Carbohydrates: "9.3 g",
      Fiber: "2.8 g",
      Sugar: "2.5 g",
      Protein: "1.1 g",
      "Vitamin C": "53 mg",
      Potassium: "138 mg",
      Calcium: "26 mg",
      Magnesium: "8 mg",
      Iron: "0.6 mg",
      Phosphorus: "16 mg",
      Zinc: "0.1 mg",
    },
    health_benefits: [
      "May support heart health",
      "May aid in digestion",
      "May boost immune system",
      "May help maintain healthy weight",
      "May have antibacterial and antiviral properties",
      "May improve skin health",
    ],
    seasonality: "Year-round",
    allergenicity: "No",
    price: "₹60 - ₹80 per kilogram",
  },
  {
    fruitName: "lettuce",
    Binomial_Name: "Lactuca sativa",
    genus: "Lactuca",
    family: "Asteraceae",
    origin: "Mediterranean region",
    fruitType: "Leafy vegetable",
    description:
      "A leafy green vegetable often used in salads and sandwiches. Lettuce has a crisp texture and mild, slightly sweet taste.",
    nutritional_information: {
      Calories: "5",
      Fat: "0.1 g",
      Carbohydrates: "1 g",
      Fiber: "0.5 g",
      Sugar: "0.4 g",
      Protein: "0.5 g",
      "Vitamin C": "4.9 mg",
      Potassium: "141 mg",
      Calcium: "18 mg",
      Magnesium: "8 mg",
      Iron: "0.3 mg",
      Phosphorus: "12 mg",
      Zinc: "0.1 mg",
    },
    health_benefits: [
      "May promote weight loss",
      "May help improve digestion",
      "May support heart health",
      "May have anti-inflammatory properties",
      "May help reduce the risk of chronic diseases",
      "May contribute to healthy skin and hair",
    ],
    seasonality: "Year-round",
    allergenicity: "No",
    price: "₹30 - ₹40 per kilogram",
  },
  {
    fruitName: "mango",
    Binomial_Name: "Mangifera indica",
    genus: "Mangifera",
    family: "Anacardiaceae",
    origin: "South Asia",
    fruitType: "Drupe",
    description:
      "A tropical fruit with a sweet, juicy flesh and a distinctive aroma. Mangoes are often called the 'king of fruits' and are enjoyed fresh, in smoothies, or in various dishes and desserts.",
    nutritional_information: {
      Calories: "60",
      Fat: "0.4 g",
      Carbohydrates: "15 g",
      Fiber: "1.6 g",
      Sugar: "14 g",
      Protein: "0.8 g",
      "Vitamin C": "36.4 mg",
      Potassium: "168 mg",
      Calcium: "10 mg",
      Magnesium: "9 mg",
      Iron: "0.2 mg",
      Phosphorus: "14 mg",
      Zinc: "0.1 mg",
    },
    health_benefits: [
      "May support immune system",
      "May aid digestion",
      "May help lower cholesterol levels",
      "May promote eye health",
      "May have anticancer properties",
      "May improve skin health",
    ],
    seasonality: "Summer",
    allergenicity: "No",
    price: "₹80 - ₹120 per kilogram",
  },
  {
    fruitName: "onion",
    Binomial_Name: "Allium cepa",
    genus: "Allium",
    family: "Amaryllidaceae",
    origin: "Asia",
    fruitType: "Bulb vegetable",
    description:
      "A bulbous vegetable with a pungent aroma and a savory flavor. Onions are widely used in cooking and come in various colors, including white, yellow, and red.",
    nutritional_information: {
      Calories: "40",
      Fat: "0.1 g",
      Carbohydrates: "9.3 g",
      Fiber: "1.7 g",
      Sugar: "4.2 g",
      Protein: "1.1 g",
      "Vitamin C": "7.4 mg",
      Potassium: "146 mg",
      Calcium: "23 mg",
      Magnesium: "10 mg",
      Iron: "0.2 mg",
      Phosphorus: "29 mg",
      Zinc: "0.2 mg",
    },
    health_benefits: [
      "May have antioxidant properties",
      "May help reduce the risk of certain cancers",
      "May support heart health",
      "May have anti-inflammatory effects",
      "May aid in blood sugar control",
      "May boost bone health",
    ],
    seasonality: "Year-round",
    allergenicity: "No",
    price: "₹30 - ₹50 per kilogram",
  },
  {
    fruitName: "orange",
    Binomial_Name: "Citrus sinensis",
    genus: "Citrus",
    family: "Rutaceae",
    origin: "Southeast Asia",
    fruitType: "Citrus",
    description:
      "A round citrus fruit known for its bright orange color and juicy, flavorful flesh. Oranges are commonly consumed fresh or used for their juice.",
    nutritional_information: {
      Calories: "43",
      Fat: "0.1 g",
      Carbohydrates: "11 g",
      Fiber: "2.4 g",
      Sugar: "9 g",
      Protein: "0.9 g",
      "Vitamin C": "53.2 mg",
      Potassium: "169 mg",
      Calcium: "40 mg",
      Magnesium: "10 mg",
      Iron: "0.1 mg",
      Phosphorus: "14 mg",
      Zinc: "0.1 mg",
    },
    health_benefits: [
      "May boost immune system",
      "May support heart health",
      "May help lower cholesterol levels",
      "May aid digestion",
      "May have anti-inflammatory properties",
      "May improve skin health",
    ],
    seasonality: "Winter",
    allergenicity: "No",
    price: "₹60 - ₹80 per kilogram",
  },
  {
    fruitName: "paprika",
    Binomial_Name: "Capsicum annuum",
    genus: "Capsicum",
    family: "Solanaceae",
    origin: "Central and South America",
    fruitType: "Pepper",
    description:
      "A spice made from ground dried peppers. Paprika is known for its vibrant red color and mild, sweet flavor.",
    nutritional_information: {
      Calories: "19",
      Fat: "0.9 g",
      Carbohydrates: "3.9 g",
      Fiber: "2 g",
      Sugar: "1.4 g",
      Protein: "0.9 g",
      "Vitamin C": "4.8 mg",
      Potassium: "175 mg",
      Calcium: "10 mg",
      Magnesium: "8 mg",
      Iron: "0.2 mg",
      Phosphorus: "20 mg",
      Zinc: "0.1 mg",
    },
    health_benefits: [
      "May have antioxidant properties",
      "May aid digestion",
      "May help lower blood pressure",
      "May have anti-inflammatory effects",
      "May support eye health",
      "May improve skin health",
    ],
    seasonality: "Year-round",
    allergenicity: "No",
    price: "₹150 - ₹200 per kilogram",
  },
  {
    fruitName: "pear",
    Binomial_Name: "Pyrus",
    genus: "Pyrus",
    family: "Rosaceae",
    origin: "Europe and Asia",
    fruitType: "Pome",
    description:
      "A sweet and juicy fruit with a characteristic pear shape and a smooth skin. Pears are available in several varieties, each with its own unique flavor and texture.",
    nutritional_information: {
      Calories: "57",
      Fat: "0.1 g",
      Carbohydrates: "15 g",
      Fiber: "3.1 g",
      Sugar: "10 g",
      Protein: "0.4 g",
      "Vitamin C": "4.2 mg",
      Potassium: "119 mg",
      Calcium: "9 mg",
      Magnesium: "7 mg",
      Iron: "0.2 mg",
      Phosphorus: "12 mg",
      Zinc: "0.1 mg",
    },
    health_benefits: [
      "May support heart health",
      "May aid digestion",
      "May help lower cholesterol levels",
      "May have antioxidant properties",
      "May improve gut health",
      "May have anti-inflammatory effects",
    ],
    seasonality: "Late Summer and Fall",
    allergenicity: "No",
    price: "₹80 - ₹120 per kilogram",
  },
  {
    fruitName: "peas",
    Binomial_Name: "Pisum sativum",
    genus: "Pisum",
    family: "Fabaceae",
    origin: "Asia",
    fruitType: "Legume",
    description:
      "Small, spherical seeds that grow in pods. Peas are commonly used as a vegetable and have a slightly sweet and earthy flavor.",
    nutritional_information: {
      Calories: "81",
      Fat: "0.4 g",
      Carbohydrates: "14 g",
      Fiber: "5 g",
      Sugar: "5 g",
      Protein: "5 g",
      "Vitamin C": "40 mg",
      Potassium: "244 mg",
      Calcium: "25 mg",
      Magnesium: "33 mg",
      Iron: "1.5 mg",
      Phosphorus: "108 mg",
      Zinc: "1.2 mg",
    },
    health_benefits: [
      "May aid in weight management",
      "May support heart health",
      "May help regulate blood sugar levels",
      "May support digestive health",
      "May have anticancer properties",
      "May promote healthy bones",
    ],
    seasonality: "Spring",
    allergenicity: "No",
    price: "₹80 - ₹100 per kilogram",
  },
  {
    fruitName: "pineapple",
    Binomial_Name: "Ananas comosus",
    genus: "Ananas",
    family: "Bromeliaceae",
    origin: "South America",
    fruitType: "Multiple fruit",
    description:
      "A tropical fruit with a spiky, rough exterior and a sweet and tangy yellow flesh. Pineapples are known for their juiciness and distinct tropical flavor.",
    nutritional_information: {
      Calories: "50",
      Fat: "0.1 g",
      Carbohydrates: "13 g",
      Fiber: "1.4 g",
      Sugar: "9.9 g",
      Protein: "0.5 g",
      "Vitamin C": "47.8 mg",
      Potassium: "180 mg",
      Calcium: "13 mg",
      Magnesium: "12 mg",
      Iron: "0.3 mg",
      Phosphorus: "8 mg",
      Zinc: "0.1 mg",
    },
    health_benefits: [
      "May support immune system",
      "May aid digestion",
      "May have anti-inflammatory effects",
      "May promote healthy skin",
      "May support eye health",
      "May have anticancer properties",
    ],
    seasonality: "Year-round",
    allergenicity: "No",
    price: "₹80 - ₹100 per kilogram",
  },
  {
    fruitName: "pomegranate",
    Binomial_Name: "Punica granatum",
    genus: "Punica",
    family: "Lythraceae",
    origin: "Middle East and South Asia",
    fruitType: "Berry",
    description:
      "A round fruit with a thick, leathery skin and hundreds of juicy red arils inside. Pomegranates have a sweet and tart flavor and are known for their antioxidant-rich properties.",
    nutritional_information: {
      Calories: "83",
      Fat: "1.2 g",
      Carbohydrates: "18.7 g",
      Fiber: "4 g",
      Sugar: "13.7 g",
      Protein: "1.7 g",
      "Vitamin C": "10.2 mg",
      Potassium: "236 mg",
      Calcium: "14 mg",
      Magnesium: "36 mg",
      Iron: "0.3 mg",
      Phosphorus: "36 mg",
      Zinc: "0.4 mg",
    },
    health_benefits: [
      "May have potent antioxidant properties",
      "May help reduce inflammation",
      "May support heart health",
      "May aid in digestion",
      "May improve memory and brain function",
      "May have anticancer properties",
    ],
    seasonality: "Fall and Winter",
    allergenicity: "No",
    price: "₹100 - ₹150 per kilogram",
  },
  {
    fruitName: "potato",
    Binomial_Name: "Solanum tuberosum",
    genus: "Solanum",
    family: "Solanaceae",
    origin: "Andes region of South America",
    fruitType: "Tuber",
    description:
      "An underground tuber with a starchy texture and a versatile flavor. Potatoes are a staple food in many cuisines and are enjoyed boiled, mashed, fried, or baked.",
    nutritional_information: {
      Calories: "77",
      Fat: "0.1 g",
      Carbohydrates: "17.5 g",
      Fiber: "2.2 g",
      Sugar: "0.8 g",
      Protein: "2 g",
      "Vitamin C": "19.7 mg",
      Potassium: "429 mg",
      Calcium: "9 mg",
      Magnesium: "23 mg",
      Iron: "0.8 mg",
      Phosphorus: "61 mg",
      Zinc: "0.4 mg",
    },
    health_benefits: [
      "May provide essential nutrients",
      "May support digestive health",
      "May have anti-inflammatory properties",
      "May help regulate blood pressure",
      "May aid in weight management",
      "May support immune function",
    ],
    seasonality: "Year-round",
    allergenicity: "No",
    price: "₹20 - ₹40 per kilogram",
  },
  {
    fruitName: "raddish",
    Binomial_Name: "Raphanus sativus",
    genus: "Raphanus",
    family: "Brassicaceae",
    origin: "Asia",
    fruitType: "Root vegetable",
    description:
      "A root vegetable with a crisp texture and a peppery flavor. Radishes come in various colors, including red, white, and black, and can be enjoyed raw or cooked.",
    nutritional_information: {
      Calories: "16",
      Fat: "0.1 g",
      Carbohydrates: "3.4 g",
      Fiber: "1.6 g",
      Sugar: "1.9 g",
      Protein: "0.7 g",
      "Vitamin C": "14.8 mg",
      Potassium: "233 mg",
      Calcium: "25 mg",
      Magnesium: "10 mg",
      Iron: "0.3 mg",
      Phosphorus: "20 mg",
      Zinc: "0.3 mg",
    },
    health_benefits: [
      "May support digestion",
      "May have diuretic properties",
      "May help regulate blood pressure",
      "May have detoxifying effects",
      "May promote hydration",
      "May have anticancer properties",
    ],
    seasonality: "Spring and Fall",
    allergenicity: "No",
    price: "₹30 - ₹40 per kilogram",
  },
  {
    fruitName: "soy beans",
    Binomial_Name: "Glycine max",
    genus: "Glycine",
    family: "Fabaceae",
    origin: "East Asia",
    fruitType: "Legume",
    description:
      "Edible beans that are commonly used in various forms, such as tofu, soy milk, and tempeh. Soy beans have a high protein content and are a staple in vegetarian and vegan diets.",
    nutritional_information: {
      Calories: "173",
      Fat: "9 g",
      Carbohydrates: "10 g",
      Fiber: "6 g",
      Sugar: "3 g",
      Protein: "17 g",
      "Vitamin C": "6 mg",
      Potassium: "539 mg",
      Calcium: "102 mg",
      Magnesium: "86 mg",
      Iron: "3.6 mg",
      Phosphorus: "241 mg",
      Zinc: "2.2 mg",
    },
    health_benefits: [
      "May support heart health",
      "May help manage cholesterol levels",
      "May aid in weight management",
      "May support bone health",
      "May have anticancer properties",
      "May help alleviate menopause symptoms",
    ],
    seasonality: "Year-round",
    allergenicity: "Yes",
    price: "₹80 - ₹100 per kilogram",
  },
  {
    fruitName: "spinach",
    Binomial_Name: "Spinacia oleracea",
    genus: "Spinacia",
    family: "Amaranthaceae",
    origin: "Central and Western Asia",
    fruitType: "Leafy green",
    description:
      "A leafy green vegetable with dark green leaves that are tender and flavorful. Spinach is commonly used in salads, cooked dishes, and smoothies.",
    nutritional_information: {
      Calories: "23",
      Fat: "0.4 g",
      Carbohydrates: "3.6 g",
      Fiber: "2.2 g",
      Sugar: "0.4 g",
      Protein: "2.9 g",
      "Vitamin C": "28.1 mg",
      Potassium: "558 mg",
      Calcium: "99 mg",
      Magnesium: "79 mg",
      Iron: "2.7 mg",
      Phosphorus: "49 mg",
      Zinc: "0.5 mg",
    },
    health_benefits: [
      "May support eye health",
      "May promote brain health",
      "May help regulate blood pressure",
      "May support bone health",
      "May aid in digestion",
      "May have anticancer properties",
    ],
    seasonality: "Spring and Fall",
    allergenicity: "No",
    price: "₹20 - ₹30 per kilogram",
  },
  {
    fruitName: "sweetcorn",
    Binomial_Name: "Zea mays",
    genus: "Zea",
    family: "Poaceae",
    origin: "Mexico",
    fruitType: "Grain",
    description:
      "A variety of maize with kernels that are sweet, tender, and juicy. Sweetcorn is often consumed as a vegetable and can be boiled, grilled, or steamed.",
    nutritional_information: {
      Calories: "86",
      Fat: "1.2 g",
      Carbohydrates: "18 g",
      Fiber: "2 g",
      Sugar: "3.2 g",
      Protein: "3.3 g",
      "Vitamin C": "6.8 mg",
      Potassium: "270 mg",
      Calcium: "2 mg",
      Magnesium: "37 mg",
      Iron: "0.5 mg",
      Phosphorus: "89 mg",
      Zinc: "0.6 mg",
    },
    health_benefits: [
      "May support eye health",
      "May aid digestion",
      "May have anticancer properties",
      "May help regulate blood sugar levels",
      "May support heart health",
      "May promote healthy skin",
    ],
    seasonality: "Summer",
    allergenicity: "No",
    price: "₹40 - ₹60 per kilogram",
  },
  {
    fruitName: "sweetpotato",
    Binomial_Name: "Ipomoea batatas",
    genus: "Ipomoea",
    family: "Convolvulaceae",
    origin: "Central and South America",
    fruitType: "Tuber",
    description:
      "An underground tuber with a sweet and starchy flesh and a thin, edible skin. Sweet potatoes are rich in nutrients and are often used as a healthier alternative to regular potatoes.",
    nutritional_information: {
      Calories: "86",
      Fat: "0.1 g",
      Carbohydrates: "20.1 g",
      Fiber: "3 g",
      Sugar: "4.2 g",
      Protein: "1.6 g",
      "Vitamin C": "2.4 mg",
      Potassium: "337 mg",
      Calcium: "30 mg",
      Magnesium: "25 mg",
      Iron: "0.8 mg",
      Phosphorus: "47 mg",
      Zinc: "0.3 mg",
    },
    health_benefits: [
      "May support digestive health",
      "May have anti-inflammatory properties",
      "May help regulate blood sugar levels",
      "May support eye health",
      "May boost immune function",
      "May have anticancer properties",
    ],
    seasonality: "Fall",
    allergenicity: "No",
    price: "₹40 - ₹60 per kilogram",
  },
  {
    fruitName: "tomato",
    Binomial_Name: "Solanum lycopersicum",
    genus: "Solanum",
    family: "Solanaceae",
    origin: "South America",
    fruitType: "Berry",
    description:
      "A juicy fruit with a vibrant red color and a tangy flavor. Tomatoes are versatile and used in various cuisines, including salads, sauces, and soups.",
    nutritional_information: {
      Calories: "18",
      Fat: "0.2 g",
      Carbohydrates: "3.9 g",
      Fiber: "1.2 g",
      Sugar: "2.6 g",
      Protein: "0.9 g",
      "Vitamin C": "14.8 mg",
      Potassium: "237 mg",
      Calcium: "10 mg",
      Magnesium: "11 mg",
      Iron: "0.3 mg",
      Phosphorus: "24 mg",
      Zinc: "0.2 mg",
    },
    health_benefits: [
      "May support heart health",
      "May have anticancer properties",
      "May promote skin health",
      "May support eye health",
      "May have anti-inflammatory effects",
      "May aid digestion",
    ],
    seasonality: "Summer",
    allergenicity: "No",
    price: "₹20 - ₹40 per kilogram",
  },
  {
    fruitName: "turnip",
    Binomial_Name: "Brassica rapa subsp. rapa",
    genus: "Brassica",
    family: "Brassicaceae",
    origin: "Mediterranean region",
    fruitType: "Root vegetable",
    description:
      "A root vegetable with a white or purple skin and a crisp texture. Turnips have a slightly sweet and earthy flavor and can be eaten raw or cooked.",
    nutritional_information: {
      Calories: "28",
      Fat: "0.1 g",
      Carbohydrates: "6.4 g",
      Fiber: "1.8 g",
      Sugar: "3.8 g",
      Protein: "0.9 g",
      "Vitamin C": "21 mg",
      Potassium: "233 mg",
      Calcium: "30 mg",
      Magnesium: "10 mg",
      Iron: "0.3 mg",
      Phosphorus: "27 mg",
      Zinc: "0.2 mg",
    },
    health_benefits: [
      "May support digestion",
      "May have diuretic properties",
      "May help regulate blood pressure",
      "May support immune function",
      "May have anticancer properties",
      "May promote bone health",
    ],
    seasonality: "Fall and Winter",
    allergenicity: "No",
    price: "₹30 - ₹40 per kilogram",
  },
  {
    fruitName: "watermelon",
    Binomial_Name: "Citrullus lanatus",
    genus: "Citrullus",
    family: "Cucurbitaceae",
    origin: "Africa",
    fruitType: "Melon",
    description:
      "A large fruit with a thick rind and sweet, juicy flesh. Watermelon is a refreshing summer fruit and is commonly consumed as a snack or in fruit salads.",
    nutritional_information: {
      Calories: "30",
      Fat: "0.2 g",
      Carbohydrates: "7.6 g",
      Fiber: "0.6 g",
      Sugar: "6.2 g",
      Protein: "0.6 g",
      "Vitamin C": "8.1 mg",
      Potassium: "112 mg",
      Calcium: "7 mg",
      Magnesium: "10 mg",
      Iron: "0.3 mg",
      Phosphorus: "11 mg",
      Zinc: "0.1 mg",
    },
    health_benefits: [
      "May support hydration",
      "May help cool the body",
      "May have anti-inflammatory effects",
      "May promote heart health",
      "May support healthy skin",
      "May aid digestion",
    ],
    seasonality: "Summer",
    allergenicity: "No",
    price: "₹20 - ₹30 per kilogram",
  },
  {
    fruitName: "bell pepper",
    Binomial_Name: "Capsicum annuum",
    genus: "Capsicum",
    family: "Solanaceae",
    origin: "Central and South America",
    fruitType: "Vegetable",
    description:
      "A sweet and crunchy fruit with various colors, including red, yellow, and green. Bell peppers are commonly used in salads, stir-fries, and as a pizza topping.",
    nutritional_information: {
      Calories: "31",
      Fat: "0.3 g",
      Carbohydrates: "6 g",
      Fiber: "2.1 g",
      Sugar: "4.2 g",
      Protein: "1.3 g",
      "Vitamin C": "152 mg",
      Potassium: "211 mg",
      Calcium: "10 mg",
      Magnesium: "12 mg",
      Iron: "0.4 mg",
      Phosphorus: "22 mg",
      Zinc: "0.2 mg",
    },
    health_benefits: [
      "May support eye health",
      "May have anti-inflammatory properties",
      "May boost immune function",
      "May support heart health",
      "May promote digestion",
      "May have anticancer properties",
    ],
    seasonality: "Summer and Fall",
    allergenicity: "No",
    price: "₹60 - ₹80 per kilogram",
  },
  {
    fruitName: "cabbage",
    Binomial_Name: "Brassica oleracea var. capitata",
    genus: "Brassica",
    family: "Brassicaceae",
    origin: "Mediterranean region",
    fruitType: "Vegetable",
    description:
      "A leafy vegetable with dense, layered leaves. Cabbage is often used in salads, coleslaw, and cooked dishes such as stir-fries and soups.",
    nutritional_information: {
      Calories: "25",
      Fat: "0.1 g",
      Carbohydrates: "6 g",
      Fiber: "2.5 g",
      Sugar: "3.2 g",
      Protein: "1.3 g",
      "Vitamin C": "36.6 mg",
      Potassium: "170 mg",
      Calcium: "40 mg",
      Magnesium: "12 mg",
      Iron: "0.4 mg",
      Phosphorus: "26 mg",
      Zinc: "0.2 mg",
    },
    health_benefits: [
      "May support digestive health",
      "May have anti-inflammatory properties",
      "May boost immune function",
      "May promote heart health",
      "May have anticancer properties",
      "May aid detoxification",
    ],
    seasonality: "Fall and Winter",
    allergenicity: "No",
    price: "₹30 - ₹40 per kilogram",
  },
  {
    fruitName: "capsicum",
    Binomial_Name: "Capsicum annuum",
    genus: "Capsicum",
    family: "Solanaceae",
    origin: "Central and South America",
    fruitType: "Vegetable",
    description:
      "A mildly spicy fruit with various colors, including red, yellow, and green. Capsicums are commonly used in salads, stir-fries, and as a pizza topping.",
    nutritional_information: {
      Calories: "26",
      Fat: "0.3 g",
      Carbohydrates: "6 g",
      Fiber: "2.1 g",
      Sugar: "4.2 g",
      Protein: "0.9 g",
      "Vitamin C": "80.4 mg",
      Potassium: "211 mg",
      Calcium: "10 mg",
      Magnesium: "12 mg",
      Iron: "0.3 mg",
      Phosphorus: "22 mg",
      Zinc: "0.2 mg",
    },
    health_benefits: [
      "May support eye health",
      "May have anti-inflammatory properties",
      "May boost immune function",
      "May support heart health",
      "May promote digestion",
      "May have anticancer properties",
    ],
    seasonality: "Summer and Fall",
    allergenicity: "No",
    price: "₹80 - ₹100 per kilogram",
  },
  {
    fruitName: "carrot",
    Binomial_Name: "Daucus carota",
    genus: "Daucus",
    family: "Apiaceae",
    origin: "Afghanistan",
    fruitType: "Vegetable",
    description:
      "A root vegetable with a crunchy texture and a sweet, earthy flavor. Carrots are commonly eaten raw, cooked, or juiced.",
    nutritional_information: {
      Calories: "41",
      Fat: "0.2 g",
      Carbohydrates: "10 g",
      Fiber: "2.8 g",
      Sugar: "4.7 g",
      Protein: "0.9 g",
      "Vitamin C": "5.9 mg",
      Potassium: "320 mg",
      Calcium: "33 mg",
      Magnesium: "12 mg",
      Iron: "0.3 mg",
      Phosphorus: "35 mg",
      Zinc: "0.2 mg",
    },
    health_benefits: [
      "May support eye health",
      "May promote skin health",
      "May boost immune function",
      "May support heart health",
      "May aid digestion",
      "May have anticancer properties",
    ],
    seasonality: "Year-round",
    allergenicity: "No",
    price: "₹40 - ₹50 per kilogram",
  },
  {
    fruitName: "cauliflower",
    Binomial_Name: "Brassica oleracea var. botrytis",
    genus: "Brassica",
    family: "Brassicaceae",
    origin: "Mediterranean region",
    fruitType: "Vegetable",
    description:
      "A cruciferous vegetable with a compact head made up of undeveloped flower buds. Cauliflower is often used as a low-carb substitute for rice or in dishes such as cauliflower 'steaks' or roasted cauliflower.",
    nutritional_information: {
      Calories: "25",
      Fat: "0.3 g",
      Carbohydrates: "5 g",
      Fiber: "2 g",
      Sugar: "2.5 g",
      Protein: "2 g",
      "Vitamin C": "46.4 mg",
      Potassium: "299 mg",
      Calcium: "22 mg",
      Magnesium: "15 mg",
      Iron: "0.4 mg",
      Phosphorus: "44 mg",
      Zinc: "0.3 mg",
    },
    health_benefits: [
      "May support digestive health",
      "May have anti-inflammatory properties",
      "May boost immune function",
      "May promote heart health",
      "May have anticancer properties",
      "May aid detoxification",
    ],
    seasonality: "Fall and Winter",
    allergenicity: "No",
    price: "₹40 - ₹60 per kilogram",
  },
  {
    fruitName: "cucumber",
    Binomial_Name: "Cucumis sativus",
    genus: "Cucumis",
    family: "Cucurbitaceae",
    origin: "Southern Asia",
    fruitType: "Vegetable",
    description:
      "A long, cylindrical fruit with a crisp texture and a mild, refreshing taste. Cucumbers are commonly used in salads, pickles, and as a hydrating snack.",
    nutritional_information: {
      Calories: "16",
      Fat: "0.2 g",
      Carbohydrates: "3.6 g",
      Fiber: "0.5 g",
      Sugar: "1.8 g",
      Protein: "0.7 g",
      "Vitamin C": "2.8 mg",
      Potassium: "147 mg",
      Calcium: "16 mg",
      Magnesium: "13 mg",
      Iron: "0.3 mg",
      Phosphorus: "24 mg",
      Zinc: "0.2 mg",
    },
    health_benefits: [
      "May support hydration",
      "May promote weight loss",
      "May support heart health",
      "May aid digestion",
      "May have anti-inflammatory properties",
      "May promote skin health",
    ],
    seasonality: "Summer",
    allergenicity: "No",
    price: "₹20 - ₹30 per kilogram",
  },

  {
    fruitName: "eggplant",
    Binomial_Name: "Solanum melongena",
    genus: "Solanum",
    family: "Solanaceae",
    origin: "India",
    fruitType: "Vegetable",
    description:
      "A dark purple or black fruit with a smooth and glossy skin. Eggplants are often used in various cuisines, such as in dishes like eggplant parmesan or baba ganoush.",
    nutritional_information: {
      Calories: "25",
      Fat: "0.2 g",
      Carbohydrates: "6 g",
      Fiber: "2.5 g",
      Sugar: "3.5 g",
      Protein: "1 g",
      "Vitamin C": "2.2 mg",
      Potassium: "229 mg",
      Calcium: "9 mg",
      Magnesium: "14 mg",
      Iron: "0.2 mg",
      Phosphorus: "25 mg",
      Zinc: "0.2 mg",
    },
    health_benefits: [
      "May have antioxidant properties",
      "May support heart health",
      "May promote digestion",
      "May have anti-inflammatory properties",
      "May support brain health",
      "May aid weight management",
    ],
    seasonality: "Summer",
    allergenicity: "No",
    price: "₹40 - ₹50 per kilogram",
  },
];

export { fruitsInfo };
